language: go
os:
  - linux
  - windows

go:
  - 1.11.x

install:
  - go get github.com/stretchr/testify
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then go get golang.org/x/sys/windows; fi

script: go test -v -coverprofile cover.out -count 1 -failfast